name: fakecam
version: '2.0.0'
summary: Fakecam
description: |
  Fake background removing camera for streaming and video
  conferencing.

  https://elder.dev/posts/open-source-virtual-background/

base: core18
grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

package-repositories:
  - type: apt
    deb-types: [deb]
    components: [main]
    suites: [all]
    url: https://apt.repos.intel.com/oneapi
    key-id: 52ABD6E87E421793971873FFACFA9FC57E6C5DBE

parts:
  snapcraft-preload:
    source: https://github.com/sergiusens/snapcraft-preload.git
    plugin: cmake
    build-packages:
      - on amd64:
        - gcc-multilib
        - g++-multilib

  intel-gmmlib:
    source: https://github.com/intel/compute-runtime/releases/download/19.41.14441/intel-gmmlib_19.3.2_amd64.deb
    plugin: dump
  intel-igc-core:
    source: https://github.com/intel/compute-runtime/releases/download/19.41.14441/intel-igc-core_1.0.2597_amd64.deb
    plugin: dump
  intel-igc-opencl:
    source: https://github.com/intel/compute-runtime/releases/download/19.41.14441/intel-igc-opencl_1.0.2597_amd64.deb
    plugin: dump
  intel-ocloc:
    source: https://github.com/intel/compute-runtime/releases/download/19.41.14441/intel-ocloc_19.41.14441_amd64.deb
    plugin: dump
  intel-opencl:
    source: https://github.com/intel/compute-runtime/releases/download/19.41.14441/intel-opencl_19.41.14441_amd64.deb
    plugin: dump

  onednn:
    source: https://github.com/oneapi-src/oneDNN/releases/download/v0.21/mklml_lnx_2019.0.5.20190502.tgz
    plugin: dump
    organize:
      include: usr/include
      lib: usr/lib
      '*.txt': usr/share/doc/onednn/

  #   source: https://github.com/openvinotoolkit/oneDNN.git
  #   source-tag: v0.21_for_ie_master
  #   plugin: cmake
  #   override-pull: |
  #     snapcraftctl pull
  #     ./scripts/prepare_mkl.sh
  #   configflags:
  #     - -DCMAKE_BUILD_TYPE=Release
  #     - -DCMAKE_INSTALL_PREFIX=/usr
  #     - -DWITH_EXAMPLE=OFF
  #     - -DWITH_TEST=OFF
  #     - -DMKLDNN_USE_MKL=ON
  #     # - -DDNNL_CPU_RUNTIME=OMP
  #     # - -DDNNL_GPU_RUNTIME=OCL
  #     # - -DDNNL_BUILD_EXAMPLES=OFF
  #     # - -DDNNL_BUILD_TESTS=OFF
  #   build-environment:
  #     - CFLAGS: -O3
  #     - CXXFLAGS: -O3
  #   build-packages:
  #     - intel-oneapi-mkl-devel
  #     - wget
  #   stage-packages:
  #     - intel-oneapi-mkl

  openvino:
    after:
      - intel-gmmlib
      - intel-igc-core
      - intel-igc-opencl
      - intel-ocloc
      - intel-opencl
      - onednn
      - opencv
    source: https://github.com/openvinotoolkit/openvino.git
    plugin: cmake
    build-environment:
      - OpenCV_DIR: $SNAPCRAFT_STAGE/usr/share/OpenCV
      - CFLAGS: -O3
      - CXXFLAGS: -O3
    configflags:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DTHREADING=OMP
      - -DNGRAPH_ONNX_IMPORT_ENABLE=OFF
      - -DNGRAPH_TEST_UTIL_ENABLE=OFF
      - -DNGRAPH_TOOLS_ENABLE=OFF
      - -DENABLE_SAMPLES=OFF
      - -DENABLE_OPENCV=OFF
      - -DENABLE_PROFILING_ITT=OFF
      - -DENABLE_CLDNN=ON
      - -DENABLE_MKL_DNN=ON
      - -DGEMM=MKL
      - -DMKLROOT=$SNAPCRAFT_STAGE/opt/intel/inteloneapi/mkl/2021.1-beta06
    build-snaps:
      - cmake
    build-packages:
      - autoconf
      - automake
      - intel-oneapi-mkl-devel
      - libtool
      - libusb-1.0-0-dev
      - python
      - wget
    stage-packages:
      - intel-oneapi-mkl
      - libusb-1.0-0

  opencv:
    after:
      - intel-gmmlib
      - intel-igc-core
      - intel-igc-opencl
      - intel-ocloc
      - intel-opencl
      - onednn
    source: https://github.com/opencv/opencv.git
    source-branch: '3.4'
    plugin: cmake
    configflags:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DBUILD_opencv_apps=OFF
      - -DBUILD_TESTS=OFF
      - -DBUILD_PERF_TESTS=OFF
      - -DWITH_FFMPEG=ON
      - -DWITH_GSTREAMER=ON
      - -DWITH_VULKAN=ON
      - -DWITH_OPENCL=ON
      - -DWITH_OPENCL_SVM=ON
      - -DWITH_EIGEN=ON
      - -DWITH_LAPACK=ON
      - -DWITH_V4L=ON
      - -DWITH_VA=ON
      - -DWITH_VA_INTEL=ON
      - -DWITH_MFX=ON
      - -DWITH_MKL=ON
      - -DMKL_USE_MULTITHREAD=ON
      - -DMKL_WITH_TBB=ON
      - -DWITH_TBB=ON
      - -DWITH_IPP=ON
      - -DWITH_INF_ENGINE=ON
    build-environment:
      - CFLAGS: -O3
      - CXXFLAGS: -O3
    build-snaps:
      - cmake
    build-packages:
      - g++
      - gcc
      - intel-oneapi-mkl-devel
      # - libatlas-base-dev
      - libavcodec-dev
      - libavformat-dev
      - libavresample-dev
      # - libblas-dev
      - libeigen3-dev
      - libgstreamer-plugins-base1.0-dev
      - libgstreamer1.0-dev
      - libgtk-3-dev
      - libjpeg-dev
      - liblapack-dev
      # - libopenblas-dev
      - libopenexr-dev
      - libpng-dev
      - libswscale-dev
      - libtbb-dev
      - libtiff-dev
      - libv4l-dev
      - libva-dev
      - libvulkan-dev
      - libwebp-dev
      - linux-libc-dev
      - ocl-icd-opencl-dev
      - python3-dev
      - python3-numpy
    stage-packages:
      - intel-oneapi-mkl
      - libatlas3-base
      - libavcodec57
      - libavformat57
      - libavresample3
      # - libblas3
      - libgstreamer-plugins-base1.0-0
      - libgstreamer1.0-0
      - libjpeg8
      # - libopenblas-base
      - libopenexr22
      - libpng16-16
      - libswscale4
      - libtbb2
      - libtiff5
      - libv4l-0
      - libva2
      - libvulkan1
      - libwebp6
      - mesa-opencl-icd
      - va-driver-all

  fakecam:
    after: [opencv, openvino]
    source: fakecam
    plugin: python
    python-version: python3
    build-packages:
      - libgirepository1.0-dev
    stage-packages:
      - freeglut3
      - gir1.2-glib-2.0
      - gir1.2-gst-plugins-base-1.0
      - gir1.2-gstreamer-1.0
      - gir1.2-gtk-3.0
      - gobject-introspection
      - gstreamer1.0-gtk3
      - gstreamer1.0-plugins-good
      - libgirepository-1.0-1
      - libglu1-mesa
      - libgpm2
      - libice6
      - libslang2
      - libsm6
      - libx11-6
      - libxext6
      - libxrender1
      - python3-gi

  other-progs:
    plugin: nil
    stage-packages:
      - clinfo
      - mesa-opencl-icd
      - ocl-icd-libopencl1

  cleanup:
    after: [fakecam, other-progs]  # Make this part run last; list all your other parts here
    plugin: nil
    build-snaps: [gnome-3-28-1804, gtk-common-themes]  # List all content-snaps you're using here
    override-prime: |
      set -eux
      for snap in "gnome-3-28-1804" "gtk-common-themes"; do  # List all content-snaps you're using here
        cd "/snap/$snap/current"
        [ -d "lib" ] && find ./lib -type f,l -exec rm -f "$SNAPCRAFT_PRIME/lib/{}" "$SNAPCRAFT_PRIME/usr/lib/{}" \;
        [ -d "usr/lib" ] && find ./usr/lib -type f,l -exec rm -f "$SNAPCRAFT_PRIME/lib/{}" "$SNAPCRAFT_PRIME/usr/lib/{}" \;
        [ -d "share" ] && find ./share -type f,l -exec rm -f "$SNAPCRAFT_PRIME/share/{}" "$SNAPCRAFT_PRIME/usr/share/{}" \;
        [ -d "usr/share" ] && find ./usr/share -type f,l -exec rm -f "$SNAPCRAFT_PRIME/share/{}" "$SNAPCRAFT_PRIME/usr/share/{}" \;
      done
      for CRUFT in bug lintian man; do
        rm -rf $SNAPCRAFT_PRIME/usr/share/$CRUFT
      done
      find $SNAPCRAFT_PRIME/usr/share/doc/ -type f -not -name 'copyright' -delete
      find $SNAPCRAFT_PRIME/usr/share -type d -empty -delete

layout:
  /usr/include/clc:
    bind: $SNAP/usr/include/clc
  /usr/lib/clc:
    bind: $SNAP/usr/lib/clc
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gallium-pipe:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gallium-pipe

apps:
  clinfo:
    command: usr/bin/clinfo
    extensions: [gnome-3-28]
    plugs:
      - camera
      - desktop
      - home
      - network
      - network-bind
      - opengl
      - removable-media
      - wayland
      - x11

  fakecam:
    command: bin/fakecamcli
    extensions: [gnome-3-28]
    plugs:
      - camera
      - desktop
      - home
      - network
      - network-bind
      - opengl
      - removable-media
      - wayland
      - x11

  gui:
    command: bin/fakecamgui
    command-chain:
      - bin/snapcraft-preload
    extensions: [gnome-3-28]
    plugs:
      - camera
      - desktop
      - home
      - network
      - network-bind
      - opengl
      - removable-media
      - wayland
      - x11
