name: fakecam
version: '1.0.0'
summary: Fakecam
description: |
  Fake background removing camera for streaming and video
  conferencing.

  https://elder.dev/posts/open-source-virtual-background/

base: core18
grade: stable
confinement: strict

parts:
  bodypix:
    source: bodypix
    plugin: nodejs
    nodejs-version: '12.16.3'

  fakecam:
    source: fakecam
    plugin: python
    python-version: python3
    build-packages:
      - libgirepository1.0-dev
    stage-packages:
      - gir1.2-glib-2.0
      - gir1.2-gst-plugins-base-1.0
      - gir1.2-gstreamer-1.0
      - gir1.2-gtk-3.0
      - gobject-introspection
      - gstreamer1.0-gtk3
      - gstreamer1.0-plugins-good
      - libgirepository-1.0-1
      - libice6
      - libsm6
      - libx11-6
      - libxext6
      - libxrender1
      - python3-gi

  other-progs:
    plugin: nil
    stage-packages:
      - clinfo
      - mesa-opencl-icd
      - ocl-icd-libopencl1

  cleanup:
    after: [bodypix, fakecam, other-progs]  # Make this part run last; list all your other parts here
    plugin: nil
    build-snaps: [gnome-3-28-1804]  # List all content-snaps you're using here
    override-prime: |
      set -eux
      for snap in "gnome-3-28-1804"; do  # List all content-snaps you're using here
        cd "/snap/$snap/current" && \
          find ./lib -type f,l -exec rm -f "$SNAPCRAFT_PRIME/lib{}" "$SNAPCRAFT_PRIME/usr/lib{}" \; \
          find ./usr/lib -type f,l -exec rm -f "$SNAPCRAFT_PRIME/lib{}" "$SNAPCRAFT_PRIME/usr/lib{}" \;
      done
      for CRUFT in bug lintian man; do
        rm -rf $SNAPCRAFT_PRIME/usr/share/$CRUFT
      done
      find $SNAPCRAFT_PRIME/usr/share/doc/ -type f -not -name 'copyright' -delete
      find $SNAPCRAFT_PRIME/usr/share -type d -empty -delete

layout:
  /usr/include/clc:
    bind: $SNAP/usr/include/clc
  /usr/lib/clc:
    bind: $SNAP/usr/lib/clc
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gallium-pipe:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gallium-pipe

apps:
  clinfo:
    command: usr/bin/clinfo
    extensions: [gnome-3-28]
    plugs:
      - camera
      - desktop
      - home
      - network
      - network-bind
      - opengl
      - removable-media
      - wayland
      - x11

  fakecam:
    command: bin/fakecamcli
    extensions: [gnome-3-28]
    plugs:
      - camera
      - desktop
      - home
      - network
      - network-bind
      - opengl
      - removable-media
      - wayland
      - x11

  gui:
    command: bin/fakecamgui
    extensions: [gnome-3-28]
    environment:
      GDK_BACKEND: x11
      DISABLE_WAYLAND: 1
    plugs:
      - camera
      - desktop
      - home
      - network
      - network-bind
      - opengl
      - removable-media
      - wayland
      - x11
